config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users, only: [:destroy, :show] do
    resources :phones, only: [:new, :create]
    resources :houses, only: [:new, :create]
    resources :credits, only: [:new, :create]
    member do 
      get "mypage_pofile"
      get "mypage_identification"
      get "mypage_identification_update"
    end
  end

  resources :phones, only: [:create]
  resources :houses, only: [:update, :create]

  resources :items do
    collection do
      post 'pay/:id' => 'items#pay', as: 'pay'
    end
    member do
      get 'buy'
      get 'buy_done'
      get "flash_error"
    end
  end
  get 'users/sign_up/new' => 'users#sign_up_first' 
  get 'users/sign_up/done' => 'users#sign_up_done'
  get 'users/mypage' => 'users#mypage'
  get 'users/mypage/destroy' => 'users#mypage_session_destroy'
  get 'users/mypage/credit' => 'users#credit'
  get 'users/mypage/mypagecardtouroku' => 'users#mypagecardtouroku'
  get 'users/mypage/identification' => 'users#mypage_identification'
  get 'users/mypage/syuppin' => 'users#mypage_syuppin'
  get 'users/mypage/change_status/:id' => 'users#change_status'
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  def new
    if user_signed_in?
      if session[:aa] == 2
        @house = House.new
        session[:aa] = 3
      else
        redirect_back(fallback_location: root_path)
        flash[:alert] = "予期しないアクセスが発生しました"
      end
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "予期しないアクセスが発生しました"
    end
  end

  def create
  
    @house = House.new(house_params)
    if @house.save
      if session[:aa] == 7
        redirect_to mypage_identification_user_path(current_user)
        session[:aa] == 8
      else
        redirect_to new_user_credit_path(current_user)
      end
    else
      render action: :new
    end
  end

  def update
    @house = House.find_by(id: params[:id])
    if @house.update(house_params)
      redirect_to  mypage_identification_user_path(current_user)

    else

    end
  end
  private
  def house_params
    params.require(:house).permit(:postalcode, :prefecture,:city, :address, :building, :user_id)
  end

end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/new.html.haml
= render partial: './shared/new-header'
- if @house.errors.any?
  .errorsbox
    %h2.error-message= "#{@house.errors.full_messages.count}件のエラーが発生しました。"
= form_for @house, url: user_houses_path do |f|
  .member-main
    .member-main__container
      %h2.member-main__container__head 住所入力
      .member-main__container__form
        .member-main__container__form__top
          .form-group
            %label 郵便番号
            %span.form-group__form-require 必須
            = f.text_field :postalcode, class: "form-group__input-default",placeholder: "例) 123-4567", maxlength: "8",  pattern: "[0-9]{3}-[0-9]{4}"
          .form-group
            %label 都道府県
            %span.form-group__form-require 必須
            .form-group__prefecture
              .form-group__prefecture__ken.select-wrap
                = f.select :prefecture, [ ["--", nil], ["北海道", 1],["青森県", 2], ["岩手県", 3],["宮城県", 4],["秋田県", 5],["山形県", 6],["福島県", 7],["茨城県", 8],["栃木県", 9],["群馬県", 10],["埼玉県", 11],["千葉県", 12],["東京都", 13],["神奈川県", 14],[ "新潟県", 15],["富山県", 16],["石川県", 17],["福井県", 18],["山梨県", 19],["長野県", 20],["岐阜県", 21],["静岡県", 22],["愛知県", 23],["三重県", 24],["滋賀県", 25],["京都府", 26],["大阪府", 27],["兵庫県", 28],["奈良県", 29],["和歌山県",30],["鳥取県", 31],["島根県",32],["岡山県",33],["広島県",34],["山口県",35],["徳島県",36],["香川県",37],["愛媛県",38],["高知県",39],["福岡県",40],["佐賀県",41],["長崎県",42],["熊本県",43],["大分県",44],["宮崎県",45],["鹿児島県",46],["沖縄県",47] ], {}, class: "select-wrap__default"
                =fa_icon 'chevron-down'
          .form-group
            %label 市町村
            %span.form-group__form-require 必須
            = f.text_field :city, class: "form-group__input-default", placeholder: "例) 横浜市緑区"
          .form-group
            %label 番地
            %span.form-group__form-require 必須
            = f.text_field :address, class: "form-group__input-default", placeholder: "例) 青山-1-1-1"
          .form-group
            %label 建物名
            %span.form-group__form-any 任意
            = f.text_field :building, class: "form-group__input-default", placeholder: "例) 柳ビル101"
            = f.hidden_field :user_id, value: current_user.id
          .form-group
            %label 電話
            %span.form-group__form-any 任意
            %input.form-group__input-default{placeholder: "例) 09012345678"}
          =button_to "次へ進む",new_user_credit_path  ,method: :get, class: "member-main__container__form__top__btn" 
  = render partial: './shared/new-footer' 