config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users, only: [:destroy, :show] do
    resources :phones, only: [:new, :create]
    resources :houses, only: [:new, :create]
    resources :credits, only: [:new, :create]
    member do 
      get "mypage_pofile"
      get "mypage_identification"
      get "mypage_identification_update"
    end
  end

  resources :phones, only: [:create]
  resources :houses, only: [:update, :create]

  resources :items do
    collection do
      post 'pay/:id' => 'items#pay', as: 'pay'
    end
    member do
      get 'buy'
      get 'buy_done'
      get "flash_error"
    end
  end
  get 'users/sign_up/new' => 'users#sign_up_first' 
  get 'users/sign_up/done' => 'users#sign_up_done'
  get 'users/mypage' => 'users#mypage'
  get 'users/mypage/destroy' => 'users#mypage_session_destroy'
  get 'users/mypage/credit' => 'users#credit'
  get 'users/mypage/mypagecardtouroku' => 'users#mypagecardtouroku'
  get 'users/mypage/identification' => 'users#mypage_identification'
  get 'users/mypage/syuppin' => 'users#mypage_syuppin'
  get 'users/mypage/change_status/:id' => 'users#change_status'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  has_many :items
  validates :nickname,  presence: true
  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :family_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :city, presence: true
  validates :birthday, presence: true
  validates :password, presence: true

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first

    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
      unless user.present?
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email
        )
      end
      sns = snscredential

    else
      user = User.where(email: auth.info.email).first
      if user.present?
        sns = SnsCredential.new(
          uid: uid,
          provider: provider,
          user_id: user.id
        )
      else
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email,
        )
        sns = SnsCredential.create(
          uid: uid,
          provider: provider
        )
      end
    end
    return { user: user, sns_id: sns.id }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google_oauth2)
  end

  def callback_for(provider)
    info = User.find_oauth(request.env["omniauth.auth"])
    @user = info[:user]
    sns_id = info[:sns_id]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.sns_id"] = sns_id
      render template: "devise/registrations/new"
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end
  def user_sign_up
  end
  
  def newe
  end
  def edit
    session[:aa] = 9
  end
  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def create
     if params[:user][:password] == "" 
       params[:user][:password] = "Devise.friendly_token.first(6)" #deviseのパスワード自動生成機能を使用
       params[:user][:password_confirmation] = "Devise.friendly_token.first(6)"
       super
       sns = SnsCredential.update(user_id:  @user.id)
     else 
       super
     end
   end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_up_first
    session[:aa] = 1
  end
  def show
    if user_signed_in?
      if current_user.id == params[:id].to_i
          @address = House.find_by(user_id: current_user.id)
          session[:aa] = 6
      else
        if  "mypage"  == params[:id]
        else
          redirect_back(fallback_location: root_path)
          flash[:alert] = "先にログインして下さい"
        end
      end
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "先にログインして下さい"
    end
  end
  def mypage_identification
    if user_signed_in?
      if current_user.id == params[:id].to_i
        @address = House.find_by(user_id: current_user.id)      
        if @address == nil
          session[:aa] = 7
          @address = House.new(user_id: current_user.id)
        else
          session[:aa] = 8
          redirect_to mypage_identification_update_user_path(current_user)
        end
      else
        redirect_back(fallback_location: root_path)
        flash[:alert] = "予期しないアクセスが発生しました"
      end
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "予期しないアクセスが発生しました"
    end
  end
  def mypage_identification_update
    if user_signed_in?
      if current_user.id == params[:id].to_i
        if session[:aa] == 8
        @address =  House.find_by(user_id: current_user.id)
        else
          redirect_back(fallback_location: root_path)
          flash[:alert] = "予期しないアクセスが発生しました"
        end
      else
        redirect_back(fallback_location: root_path)
        flash[:alert] = "予期しないアクセスが発生しました"
      end
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "予期しないアクセスが発生しました"
    end
  end
  def mypage_syuppin
    @items = Item.where(user_id: current_user.id)
  end
  def change_status
    @item = Item.find(params[:id])
  end
end

app/views/users/change_status.html.haml
= render partial: "shared/topheader"
= render partial: "shared/pankuzukari"

.oobako
  .ohako
    = render partial: "shared/mypageside"
    .tisanahako
      .syuppinbox
        = form_with model: @item, local: true, class: "change-form" do |f|
          .change-form--info
            = @item.id
            = @item.name
          = link_to "商品の編集", edit_item_path(@item), class: "change-form--edit btn-red"
          .change-form--p  or
          -if @item.status == nil
            = f.hidden_field :status, value: 1
            = f.submit "出品を再開する", class: "change-form--on-sale-btn btn-red"
          -elsif @item.status == 1
            = f.hidden_field :status, value: nil
            = f.submit "出品を一旦停止する", class: "change-form--sale-stop-btn btn-gray"
          = link_to "この商品を削除する", "/items/#{@item.id}", method: "delete", class: "change-box--delete-btn btn-gray"

= render partial: "shared/topfooter"

app/views/users/credit.html.haml
= render partial: "shared/topheader"
= render partial: "shared/pankuzukari"

.oobako
  .ohako
    = render partial: "shared/mypageside"
    .ohako__content
      .ohako__content__container
        %h2.ohako__content__container__head 支払い方法
        .ohako__content__container__inner
          %section
            .ohako__content__container__inner__content
              %h3.ohako__content__container__inner__content__head クレジットカード一覧
          %section.ohako__content__container__inner__card
            .ohako__content__container__inner__card__content
              .ohako__content__container__inner__card__content__button 
                = fa_icon 'credit-card'
                = link_to users_mypage_mypagecardtouroku_path  do
                  クレジットカードを追加する

          .ohako__content__container__inner__regist
            = link_to '支払い方法について'
            = fa_icon 'angle-right'
            
= render partial: "shared/topfooter"

app/views/users/mypage.html.haml
= render partial: "shared/topheader"
= render partial: "shared/pankuzukari"

.oobako
  .ohako
    = render partial: "shared/mypageside"
    .mycontent
      .mycontent__user
        .mycontent__user__header
          .mycontent__user__header__icon
            = link_to root_path  do
              .mycontent__user__header__icon__av
                = image_tag "user_noimage.png", size: :'60x60'
              %p.mycontent__user__header__icon__name
                = current_user.nickname
              .mycontent__user__header__icon__num
                .mycontent__user__header__icon__num__rate
                  評価&emsp;&emsp;
                  %span
                    0
                .mycontent__user__header__icon__num__suu
                  出品数&emsp;&emsp;
                  %span
                    0
        .mycontent__user__tab
          %input#all{checked: :"checked", name: :"tab_item", type: :"radio"}/
          %label.tab_item{for: :"all"} お知らせ
          %input#programming{name: :"tab_item", type: :"radio"}/
          %label.tab_item{for: :"programming"} やることリスト
          #all_content.tab_content
            .tab_content_description
              %p.c-txtsp 現在、お知らせはありません
          #programming_content.tab_content
            .tab_content_description
              %p.c-txtsp 現在、やることリストはありません
        .mycontent__user__kounyuu
          購入した商品
        .mycontent__user__tab2
          %input#al{checked: :"checked", name: :"tab_torihiki", type: :"radio"}/
          %label.tab_torihiki{for: :"al"} 取引中
          %input#pro{name: :"tab_torihiki", type: :"radio"}/
          %label.tab_torihiki{for: :"pro"} 過去の取引
          #al_cont.tab_cont
            .tab_cont_description
              %p.c-txtsp 取引中の商品がありません
          #pro_cont.tab_cont
            .tab_cont_description
              %p.c-txtsp 過去に取引した商品はありません

= render partial: "shared/topfooter"

app/views/users/mypage_identification.html.haml
= render partial: "shared/topheader"
= render partial: "shared/pankuzukari"

.oobako
  .ohako
    = render partial: "shared/mypageside"
    .honnin
      .honbox
        .honbox__head
          本人情報の登録
        .honbox__main
          = form_with url: root_path,local: true , class: "sampleform" do |f|
            %p.honbox__main__head
              お客様の本人情報をご登録ください。<br>
              登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
            %a.honbox__main__caution{href: :"root_path"}
              本人確認書類のアップロードについて&emsp;＞
            .honbox__main__formbox
              %label.honbox__main__formbox__label
                お名前
              %p.honbox__main__formbox__content
                大橋      
            .honbox__main__formbox
              %label.honbox__main__formbox__label
                お名前カナ
              %p.honbox__main__formbox__content
                オオハシ
            .honbox__main__formbox
              %label.honbox__main__formbox__label
                生年月日
              %p.honbox__main__formbox__content
                1990/01/01
            .honbox__main__formbox
              %label.honbox__main__formbox__label
                郵便番号
              %span.honbox__main__formbox__nini
                任意
              = f.text_field :keyword, class: 'honbox__main__formbox__form', placeholder: '例）1234567'
            .honbox__main__formbox
              %label.honbox__main__formbox__label
                都道府県
              %span.honbox__main__formbox__nini
                任意
              %select.honbox__main__formbox__prefec
                <option value="--">--</option>
                <option value="1">北海道</option>
                <option value="2">青森県</option>
                <option value="3">岩手県</option>
                <option value="4">宮城県</option>
            .honbox__main__formbox
              %label.honbox__main__formbox__label
                市区町村
              %span.honbox__main__formbox__nini
                任意
              = f.text_field :keyword, class: 'honbox__main__formbox__form', placeholder: '例) 横浜市緑区'
            .honbox__main__formbox
              %label.honbox__main__formbox__label
                番地
              %span.honbox__main__formbox__nini
                任意
              = f.text_field :keyword, class: 'honbox__main__formbox__form', placeholder: '例) 青山1-1-1'
            .honbox__main__formbox
              %label.honbox__main__formbox__label
                建物名
              %span.honbox__main__formbox__nini
                任意
              = f.text_field :keyword, class: 'honbox__main__formbox__form', placeholder: '例) 柳ビル103'
            %button.honbox__main__btn
              登録する
            %a.honbox__main__caution{href: :"root_path"}
              本人確認書類のアップロードについて&emsp;＞

= render partial: "shared/topfooter"

app/views/users/mypage_identification_update.html.haml
= render partial: "shared/topheader"
= render partial: "shared/pankuzukari"

.oobako
  .ohako
    = render partial: "shared/mypageside"
    .honnin
      .honbox
        .honbox__head
          本人情報の登録
        .honbox__main
          %p.honbox__main__head
            お客様の本人情報をご登録ください。<br>
            登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
          %a.honbox__main__caution{href: :"root_path"}
            本人確認書類のアップロードについて&emsp;＞
          .honbox__main__formbox
            %label.honbox__main__formbox__label
              お名前
            %p.honbox__main__formbox__content
              = current_user.nickname
          .honbox__main__formbox
            %label.honbox__main__formbox__label
              お名前カナ
            %p.honbox__main__formbox__content
              = current_user.family_name_kana
              %span
              =  current_user.first_name_kana
          .honbox__main__formbox
            %label.honbox__main__formbox__label
              生年月日
            %p.honbox__main__formbox__content
              = current_user.birthday 
              %span /
              %span 
                = current_user.address
              %span /
              %span 
                = current_user.city 
          .honbox__main__formbox
            = form_for(@address, url: house_path(@address)) do |f|
              %label.honbox__main__formbox__label
              郵便番号
              %span.honbox__main__formbox__nini
                任意
              = f.text_field :postalcode, class: 'honbox__main__formbox__form', placeholder: '例）1234567'
              .honbox__main__formbox
                %label.honbox__main__formbox__label
                  都道府県
                %span.honbox__main__formbox__nini
                  任意
                = f.select :prefecture, [ ["--", nil], ["北海道", 1],["青森県", 2], ["岩手県", 3],["宮城県", 4],["秋田県", 5],["山形県", 6],["福島県", 7],["茨城県", 8],["栃木県", 9],["群馬県", 10],["埼玉県", 11],["千葉県", 12],["東京都", 13],["神奈川県", 14],[ "新潟県", 15],["富山県", 16],["石川県", 17],["福井県", 18],["山梨県", 19],["長野県", 20],["岐阜県", 21],["静岡県", 22],["愛知県", 23],["三重県", 24],["滋賀県", 25],["京都府", 26],["大阪府", 27],["兵庫県", 28],["奈良県", 29],["和歌山県",30],["鳥取県", 31],["島根県",32],["岡山県",33],["広島県",34],["山口県",35],["徳島県",36],["香川県",37],["愛媛県",38],["高知県",39],["福岡県",40],["佐賀県",41],["長崎県",42],["熊本県",43],["大分県",44],["宮崎県",45],["鹿児島県",46],["沖縄県",47] ], {}, {class: "select-default"}
              .honbox__main__formbox
                %label.honbox__main__formbox__label
                  市区町村
                %span.honbox__main__formbox__nini
                  任意
                = f.text_field :city, class: 'honbox__main__formbox__form', placeholder: '例) 横浜市緑区'
              .honbox__main__formbox
                %label.honbox__main__formbox__label
                  番地
                %span.honbox_main__formbox__nini
                  任意
                = f.text_field :address, class: 'honbox__main__formbox__form', placeholder: '例) 青山1-1-1'
              .honbox__main__formbox
                %label.honbox__main__formbox__label
                  建物名
                %span.honbox__main__formbox__nini
                  任意
                = f.text_field :building, class: 'honbox__main__formbox__form', placeholder: '例) 柳ビル103'
                = f.hidden_field  :user_id, value: current_user.id
              = f.submit class: "honbox__main__btn"
            %a.honbox__main__caution{href: :"root_path"}
              本人確認書類のアップロードについて&emsp;＞
= render partial: "shared/topfooter"

app/views/users/mypage_pofile.html.haml
= render partial: "shared/topheader"
= render partial: "shared/pankuzukari"

.oobako
  .ohako
    = render partial: "shared/mypageside"
    .profilebox
      .profilebox__head プロフィール
      %form{action: :"https://www.mercari.com/jp/mypage/profile/", method: :"POST"}
        %input{name: :"__csrf_value",type: :"hidden", value: :"d9163badd600f0759504f3c3d03fe90dc77553d7088130fd36fa09442be89f9495ac622fcdb8d50c719900926f76df4a48027fd1afba1c82a96b2020dff2aff06"}/
        .profilebox__avname
          .profilebox__avname__av
            = image_tag "user_noimage.png", size: :'60x60' 
          %input.profilebox__avname__name{name: :"nickname", placeholder: :"例)AYA☆セール中", type: :"text", value: current_user.nickname}/
        .profilebox__content
          %textarea.profilebox__content__text{name: :"introduction", placeholder: :"例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
          %input{name: :"after_save_callback", type: :"hidden", value: :"https://www.mercari.com/jp/mypage/profile/"}/
          %button.profilebox__content__btn{type: :"submit"} 変更する

= render partial: "shared/topfooter"

app/views/users/mypage_session_destroy.html.haml
= render partial: "shared/topheader"
= render partial: "shared/pankuzukari"

.oobako
  .ohako
    = render partial: "shared/mypageside"
    .logoutbox
      .logoutbox__form
        .logoutbox__form__content
          = button_to "ログアウト",  destroy_user_session_path , method: :delete , class: "logoutbox__form__content__btn"
          %input{name: :"__csrf_value", type: :"hidden", value: :"d9163badd600f0759504f3c3d03fe90dc77553d7088130fd36fa09442be89f9495ac622fcdb8d50c719900926f76df4a48027fd1afba1c82a96b2020dff2aff06"}/

= render partial: "shared/topfooter"

app/views/users/mypage_syuppin.html.haml
= render partial: "shared/topheader"
= render partial: "shared/pankuzukari"

.oobako
  .ohako
    = render partial: "shared/mypageside"
    .tisanahako
      .syuppinbox
        .syuppinbox__head
          出品した商品
        .syuppinbox__menu
          .syuppinbox__menu__1
            出品中
          .syuppinbox__menu__2
            取引中
          .syuppinbox__menu__3
            売却済み
        - @items.map do |item|
          .syuppinbox__content
            = link_to "/users/mypage/change_status/#{item.id}", class: "syuppinbox__content__link" do
              .syuppinbox__content__link__item
                = image_tag "#{item.image}", class: "img-fit"
              .syuppinbox__content__link__name
                = item.name
              - if item.status == 1
                .syuppinbox__content__link__on-sale  出品中
              - elsif item.status == nil
                .syuppinbox__content__link__sale-stop  公開停止
              .syuppinbox__content__link__icon  ＞

= render partial: "shared/topfooter"

app/views/users/mypagecardtouroku.html.haml
= render partial: "shared/topheader"
= render partial: "shared/pankuzukari"

.oobako
  .ohako
    = render partial: "shared/mypageside"
    .pay-page-single-main2
      .pay-conatainer
        %h2.pay-conatainer__head
          クレジットカード情報入力
        %form.pay-conatainer__inner
          %input{type: "hidden",method: "POST"}
          .pay-conatainer__inner__content
            .pay-conatainer__inner__content__form__card-number
              %label.pay-conatainer__inner__content__form__card-number__number-label
                カード番号
              %span.pay-conatainer__inner__content__form__card-number__require
                必須
              %input{placeholder: "半角数字のみ", maxlength:"16", class: "pay-conatainer__inner__content__form__card-number__default"}
              .pay-conatainer__inner__content__form__card-number__card-logs
                = image_tag("Visa.svg.png", class: "card-img-visa")
                = image_tag("mastercard.jpg", class: "card-img-master")
                = image_tag("saison.png", class: "card-img-saison")
                = image_tag("american.png", class: "card-img-american")
                = image_tag("diners.png", class: "card-img-diners")
                = image_tag("discover.jpg", class: "card-img")
            .pay-conatainer__inner__content__form
              %label.pay-conatainer__inner__content__form__card-number__expiration-date-label
                有効期限
              %span.pay-conatainer__inner__content__form__card-number__require
                必須
              .pay-conatainer__inner__content__form__select-wrap
                .pay-conatainer__inner__content__form__select-wrap__select-month
                  %select{name: "month", class: "select-default"}
                    %option{value: "0"}--
                    %option{value: "1"}1
                    %option{value: "2"}2
                    %option{value: "3"}3
                    %option{value: "4"}4
                    %option{value: "5"}5
                    %option{value: "6"}6
                    %option{value: "7"}7
                    %option{value: "8"}8
                    %option{value: "9"}9
                    %option{value: "10"}10
                    %option{value: "11"}11
                    %option{value: "12"}12
                  %i.fa.fa-chevron-down
                  %span.pay-conatainer__inner__content__form__select-wrap__text-month
                    月
                .pay-conatainer__inner__content__form__select-wrap__select-month
                  %select{name: "year", class: "select-default"}
                    %option{value: "0"}--
                    %option{value: "19"}19
                    %option{value: "20"}20
                    %option{value: "21"}21
                    %option{value: "22"}22
                    %option{value: "23"}23
                    %option{value: "24"}24
                    %option{value: "25"}25
                    %option{value: "26"}26
                    %option{value: "27"}27
                    %option{value: "28"}28
                    %option{value: "29"}29
                    %option{value: "30"}30
                    %option{value: "31"}31
                  %i.fa.fa-chevron-down
                  %span.pay-conatainer__inner__content__form__select-wrap__text-month
                    年
                .pay-conatainer__inner__content__form__select-wrap__year
                  
            .pay-conatainer__inner__content__form
              %label.pay-conatainer__inner__content__form__card-number__securty-label
                セキュリティコード
              %span.pay-conatainer__inner__content__form__card-number__require
                必須
              %input{placeholder: "カード背面4桁もしくは3桁の番号", maxlength:"4", class: "pay-conatainer__inner__content__form__card-number__default"}
              .pay-conatainer__inner__content__form__hatena
                = link_to 'カード裏面の番号とは？'
          .pay-conatainer__inner__content
            %input{type: "hidden", method: "POST"}
            %button{type: "submit", class:"nextbtn-red"}
              追加する

= render partial: "shared/topfooter"

app/views/users/profile.html.haml
= render partial: "shared/topheader"
= render partial: "shared/pankuzukari"

.oobako
  .ohako
    = render partial: "shared/mypageside"
    .profilebox
      .profilebox__head プロフィール
      %form{action: :"https://www.mercari.com/jp/mypage/profile/", method: :"POST"}
        %input{name: :"__csrf_value",type: :"hidden", value: :"d9163badd600f0759504f3c3d03fe90dc77553d7088130fd36fa09442be89f9495ac622fcdb8d50c719900926f76df4a48027fd1afba1c82a96b2020dff2aff06"}/
        .profilebox__avname
          .profilebox__avname__av
            = image_tag "user_noimage.png", size: :'60x60' 
          %input.profilebox__avname__name{name: :"nickname", placeholder: :"例)AYA☆セール中", type: :"text", value: :"大橋"}/
        .profilebox__content
          %textarea.profilebox__content__text{name: :"introduction", placeholder: :"例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
          %input{name: :"after_save_callback", type: :"hidden", value: :"https://www.mercari.com/jp/mypage/profile/"}/
          %button.profilebox__content__btn{type: :"submit"} 変更する

= render partial: "shared/topfooter"

app/views/users/sign_up1.html.haml
= render partial: './shared/new-header'

.new-main
  .new-main__container
    %h2.new-main__container__head
      新規会員登録
  .new-main__inner
    .new-main__inner__content
      = link_to new_user_registration_path,  class:"new-main--link" do
        %p.new-main__inner__content__mail
          =fa_icon 'envelope-o'
          メールアドレスで登録
    .new-main__inner__content__facebook
      = link_to user_facebook_omniauth_authorize_path class:"new-main--link" do
        %p.new-main__inner__content__facebook__icon
          =fa_icon 'facebook-official'
          Facebookで登録
    .new-main__inner__content__google
      = link_to user_google_oauth2_omniauth_authorize_path class:"new-main--link" do
        %p.new-main__inner__content__google__icon
          = image_tag "google.jpg", class:"image", alt:"merucari",  size: "20x20" 
          Googleで登録
= render partial: 'shared/new-footer'