config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users, only: [:destroy, :show] do
    resources :phones, only: [:new, :create]
    resources :houses, only: [:new, :create]
    resources :credits, only: [:new, :create]
    member do 
      get "mypage_pofile"
      get "mypage_identification"
      get "mypage_identification_update"
    end
  end

  resources :phones, only: [:create]
  resources :houses, only: [:update, :create]

  resources :items do
    collection do
      post 'pay/:id' => 'items#pay', as: 'pay'
    end
    member do
      get 'buy'
      get 'buy_done'
      get "flash_error"
    end
  end
  get 'users/sign_up/new' => 'users#sign_up_first' 
  get 'users/sign_up/done' => 'users#sign_up_done'
  get 'users/mypage' => 'users#mypage'
  get 'users/mypage/destroy' => 'users#mypage_session_destroy'
  get 'users/mypage/credit' => 'users#credit'
  get 'users/mypage/mypagecardtouroku' => 'users#mypagecardtouroku'
  get 'users/mypage/identification' => 'users#mypage_identification'
  get 'users/mypage/syuppin' => 'users#mypage_syuppin'
  get 'users/mypage/change_status/:id' => 'users#change_status'
end

app/views/shared/_mypageside.html.haml
.sidebar
  %nav.sidebar__nav
    %ul.sidbar__nav__list
      %li
        = link_to users_mypage_path,class: "sidebar__nav__list__ichi"  do
          マイページ
          = fa_icon 'angle-right', class: 'icon'
      %li
        = link_to root_path,class: "sidebar__nav__list__ichi"  do
          お知らせ
          = fa_icon 'angle-right', class: 'icon'
      %li
        = link_to root_path,class: "sidebar__nav__list__ichi"  do
          やることリスト
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to root_path,class: "sidebar__nav__list__ichi"  do
          いいね！一覧
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to new_item_path,class: "sidebar__nav__list__ichi"  do
          出品する
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to users_mypage_syuppin_path,class: "sidebar__nav__list__ichi"  do
          出品した商品-出品中
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to root_path,class: "sidebar__nav__list__ichi"  do
          出品した商品-取引中
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to root_path,class: "sidebar__nav__list__ichi"  do
          出品した商品-売却済み
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to root_path,class: "sidebar__nav__list__ichi"  do
          購入した商品-取引中
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to root_path,class: "sidebar__nav__list__ichi"  do
          購入した商品-過去の取り引き
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to root_path,class: "sidebar__nav__list__ichi"  do
          ニュース一覧
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to root_path,class: "sidebar__nav__list__ichi"  do
          評価一覧
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to root_path,class: "sidebar__nav__list__ichi"  do
          ガイド
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to root_path,class: "sidebar__nav__list__ichi"  do
          お問い合わせ
          = fa_icon 'angle-right', class: 'migiya'
    %h3.sidebar__nav__head
      メルペイ
    %ul.sidbar__nav__list
      %li
        = link_to root_path,class: "sidebar__nav__list__ichi"  do
          売上・振込申請
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to root_path,class: "sidebar__nav__list__ichi"  do
          ポイント
          = fa_icon 'angle-right', class: 'migiya'
    %h3.sidebar__nav__head
      設定
    %ul.sidbar__nav__list
      %li
        = link_to  mypage_pofile_user_path(current_user) ,class: "sidebar__nav__list__ichi"  do
          プロフィール
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to root_path,class: "sidebar__nav__list__ichi"  do
          発送元・お届け先住所変更
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to users_mypage_credit_path,class: "sidebar__nav__list__ichi"  do
          支払い方法
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to  edit_user_registration_path,class: "sidebar__nav__list__ichi"  do
          メール/パスワード
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to mypage_identification_user_path(current_user) ,class: "sidebar__nav__list__ichi"  do
          本人情報
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to root_path,class: "sidebar__nav__list__ichi"  do
          電話番号の確認
          = fa_icon 'angle-right', class: 'migiya'
      %li
        = link_to  users_mypage_destroy_path,class: "sidebar__nav__list__ichi"  do
          ログアウト
          = fa_icon 'angle-right', class: 'migiya'

app/views/shared/_new-footer.html.haml
.check-footer
  .check-footer__nav
    %li  
      = link_to 'プライバシーポリシー', 'https://www.mercari.com/jp/privacy/'
    %li
      = link_to 'メルカリ利用規約', 'https://www.mercari.com/jp/tos/'
    %li
      = link_to '特定商取引に関する表記', 'https://www.mercari.com/jp/tokutei/'
  = link_to  do
    = image_tag "merucari_icon2.svg", class:"image", alt:"merucari",  size: "80x65"
  %p  © 2019 Mercari

app/views/shared/_new-header.html.haml
.check-header
  %h
    = link_to root_path do 
      = image_tag "merucari_icon.svg", class:"image", alt:"merucari",  size: "185x49"

app/views/shared/_pankuzukari.html.haml
%nav.karinav
  %ul.karinav__list
    %li.karinav__list--breadcrumbs
      - case params.values_at :controller, :action
      - when ['users','show']
        - breadcrumb :user
      - when ['users','mypage_session_destroy']
        - breadcrumb :user_logout
      - when ['users','mypage_pofile']
        - breadcrumb :user_profile
      - when ['users','credit']
        - breadcrumb :user_credit
      - when ['users','mypage_identification']
        - breadcrumb :user_identification
      - when ['users','mypage_syuppin']
        - breadcrumb :user_syuppin
      - when ['users/registrations','edit']
        - breadcrumb :user_edit
      = breadcrumbs separator: "  ＞  "

app/views/shared/_topfooter.html.haml
.default-container
  .content-footer
    .app-banner
      = image_tag "banar-image.png", class: "app-banar-img"
    %footer.footer-top-page
      .footer-box
        .footer-cell
          %h2.footer-cell__head メルカリについて
          %ul
            %li.footer-cell__footer-top-text-normal 会社概要 (運営会社)
            %li.footer-cell__normal 採用情報
            %li.footer-cell__normal プレリリース
            %li.footer-cell__normal 公式ブログ
            %li.footer-cell__normal メルカリロゴ利用ガイドライン
            %li.footer-cell__sns-link
              = fa_icon 'twitter', class: "twitter-logo"
            %li.footer-cell__sns-link
              = fa_icon 'facebook-square', class: "twitter-logo"
        .footer-cell
          %h2.footer-cell__head ヘルプ＆ガイド
          %ul
            %li.footer-cell__footer-top-text-normal メルカリガイド
            %li.footer-cell__normal 楽々メルカリ便
            %li.footer-cell__normal ゆうゆうメルカリ便
            %li.footer-cell__normal 大型メルカリ便
            %li.footer-cell__normal 車体取引ガイド
            %li.footer-cell__normal メルカリあんしん・あんぜん宣言
            %li.footer-cell__normal 偽ブランド品撲滅への取り組み
            %li.footer-cell__normal メルカリボックス
        .footer-cell-full-width
          %h2.footer-cell-full-width__head プライバシーと利用規約
          .footer-cell-full-width__cell-wrapper
            .footer-cell-full-width__cell-wrapper__cell-left
              %ul
                %li.footer-cell-full-width__cell-wrapper__cell-left__top-text-normal プライバシーポリシー
                %li.footer-cell-full-width__cell-wrapper__cell-left__normal メルカリ利用規約
                %li.footer-cell-full-width__cell-wrapper__cell-left__normal あんしんスマホサポート制度に関する利用規約
                %li.footer-cell-full-width__cell-wrapper__cell-left__normal コンプライアンスポリシー
            .footer-cell-full-width__cell-wrapper__cell-right
              %ul
                %li.footer-cell-full-width__cell-wrapper__cell-right__top-text-normal 個人データの安全管理に係る基本方針
                %li.footer-cell-full-width__cell-wrapper__cell-right__normal 特定商取引に関する表記
                %li.footer-cell-full-width__cell-wrapper__cell-right__normal 資金決済法に基づく表示
                %li.footer-cell-full-width__cell-wrapper__cell-right__normal 法令遵守と犯罪抑止のために
                %li.footer-cell-full-width__cell-wrapper__cell-right__normal 返品・返金ポリシー
        .fotter-cell-lang
          %h2.footer-cell__head 国
          %ul
            %li.footer-head-jp 日本
            %li.footer-head-us United Status
      .footer-bottom
        = link_to root_path class:"footer-logo-link" do
          - image_tag "logo-white.svg", class: "footer-logo-link-image"
        %span.footer-copyrifght © 2019 Mercari
      = link_to root_path, class: "footer-sell-btn" do
        .footer-sell-btn__text 出品
        = fa_icon "camera", class: "camera-icon"

app/views/shared/_topheader.html.haml
%body
  .default-container
    %header.top-page-pc-header
      .top-page-pc-header__inner
        .top-page-pc-header__inner__top
          %h1.top-page-pc-header__inner__top__logo
            = link_to image_tag('top-header-logo.svg', class: "header-logo" ), root_path
          .header-search-form
            %input{class: "header-search-form__input", placeholder: "何かお探しですか？"}
              = link_to root_path, class:"header-search-button"  do
                .header-button-wrapper
                  = fa_icon 'search 2x', class: "search"
        .top-page-header-icon-lists
          .top-icon-list-left
            %ul.header-category-wrapper
              %li.header-icons
                %h2
                  = link_to root_path class:"pc-header-nav-rootlist-parent" do
                    = fa_icon("list-ul", class: "header-left-icon-logo")
                    %span.header-bold カテゴリーから探す
              %li.header-icons
                %h2
                  = link_to root_path class:"pc-header-nav-root list-parent" do
                    = fa_icon("tag", class: "header-left-icon-logo")
                    %span.header-bold ブランドから探す
          .top-page-list-right
            %ul.header-user-nav
              %li.header-info
                = link_to root_path class: "header-info-link" do
                  = fa_icon("bell-o ")
                  %span.header-user-nav-text お知らせ
              %li.header-to-do
                = link_to root_path class: "to_do-link" do
                  = fa_icon("check")
                  %span.header-user-nav-text やることリスト
              %li.header-mypage
                = link_to users_mypage_path class: "header-my-page-link" do
                  = image_tag "mypage-image.png", class: "header-mypage-icon-image"
                  %span.header-user-nav-text-mypage マイページ