config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users, only: [:destroy, :show] do
    resources :phones, only: [:new, :create]
    resources :houses, only: [:new, :create]
    resources :credits, only: [:new, :create]
    member do 
      get "mypage_pofile"
      get "mypage_identification"
      get "mypage_identification_update"
    end
  end

  resources :phones, only: [:create]
  resources :houses, only: [:update, :create]

  resources :items do
    collection do
      post 'pay/:id' => 'items#pay', as: 'pay'
    end
    member do
      get 'buy'
      get 'buy_done'
      get "flash_error"
    end
  end
  get 'users/sign_up/new' => 'users#sign_up_first' 
  get 'users/sign_up/done' => 'users#sign_up_done'
  get 'users/mypage' => 'users#mypage'
  get 'users/mypage/destroy' => 'users#mypage_session_destroy'
  get 'users/mypage/credit' => 'users#credit'
  get 'users/mypage/mypagecardtouroku' => 'users#mypagecardtouroku'
  get 'users/mypage/identification' => 'users#mypage_identification'
  get 'users/mypage/syuppin' => 'users#mypage_syuppin'
  get 'users/mypage/change_status/:id' => 'users#change_status'
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader

  enum condition:{"新品、未使用": 1, "未使用に近い": 2, "目立った傷や汚れなし": 3, "やや傷や汚れあり": 4, "傷や汚れあり": 5, "全体的に状態が悪い": 6} 
  enum delivery_fee:{"着払い（購入者負担）": 1, "送料込み（出品者負担）": 2}
  enum delivery_method:{"未定": 1, "らくらくメルカリ便": 2}
  enum delivery_days:{"１〜２日で発送": 1, "２〜３日で発送": 2, "４〜７日で発送": 3}
  enum size:{"XS": 1, "S": 2, "M": 3, "L": 4, "XL": 5}
  enum prefecture:{"北海道": 1, "青森県": 2, "岩手県": 3, "宮城県": 4, "秋田県": 5, "山形県": 6, "福島県": 7, "茨城県": 8, "栃木県": 9, "群馬県": 10, "埼玉県": 11, "千葉県": 12, "東京都": 13, "神奈川県": 14, "新潟県": 15, "富山県": 16, "石川県": 17, "福井県": 18, "山梨県": 19, "長野県": 20, "岐阜県": 21,"静岡県":22, "愛知県":23, "三重県 ":24, "滋賀県 ":25, "京都府 ":26, "大阪府 ":27, "兵庫県 ":28, "奈良県 ":29, "和歌山県 ":30, "鳥取県 ":31, "島根県":32, "岡山県":33, "広島県":34, "山口県":35, "徳島県":36, "香川県":37, "愛媛県":38, "高知県":39, "福岡県":40, "佐賀県":41, "長崎県":42, "熊本県":43, "大分県":44, "宮崎県":45, "鹿児島県":46, "沖縄県":47}

  # has_many :images
  # belongs_to :brand
  # belongs_to :category
  belongs_to :user

  validates :name, presence: true
  validates :discription, presence: true
  validates :condition, presence: true
  validates :delivery_fee, presence: true
  validates :delivery_method, presence: true
  validates :delivery_days, presence: true
  validates :price, presence: true
  validates :prefecture, presence: true
  validates :image, presence: true
  validates :category, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show,:edit,:update,:destroy, :buy, :buy_done, :flash_error]
  def flash_error  
    @items = Item.order('id DESC').limit(3)
  end

  def index
    session[:aa] = 00
    @items = Item.where(status: 1).order('id DESC').limit(4)
    @ladys = Item.where(status: 1,category: 1).order('id DESC').limit(4)
    @mens = Item.where(status: 1,category: 2).order('id DESC').limit(4)
    @babys = Item.where(status: 1,category: 3).order('id DESC').limit(4)
    @biyous = Item.where(status: 1,category: 4).order('id DESC').limit(4)
    @shanels =Item.where(status: 1,brand: "シャネル").or(Item.where(brand: "CHANEL")).or(Item.where(brand: "chanel")).or(Item.where(brand: "しゃねる")).order('id DESC').limit(4)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
      flash[:notice] = "出品が完了しました"
    else
      render action: :new
    end
  end
  
  def show
    @items = Item.where(user_id: @item.user_id).order('id DESC').limit(3)
  end

  def edit 
    if user_signed_in?
      if @item.user_id == current_user.id

      else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "予期しないアクセスが発生しました"
      end
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "予期しないアクセスが発生しました"
    end
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
      flash[:notice] = "編集が完了しました"
    else
      render  action: :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      redirect_to action: "flash_error"
    end
  end

  def detail
  end

  def buy_confirmation
  end
  
  def buy
    if user_signed_in?
      if @item.buyer_number == nil
      else
        redirect_back(fallback_location: root_path)
        flash[:alert] = "予期しないアクセスが発生しました"
      end
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "予期しないアクセスが発生しました"
    end
  end
  
  def buy_done
    if user_signed_in?
    if current_user.id == @item.buyer_number
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "予期しないアクセスが発生しました"
    end
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "予期しないアクセスが発生しました"
    end
  end  

  def pay
    item = Item.find(params[:id])
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    Payjp::Charge.create(currency: 'jpy', amount: item.price, card: params['payjp-token'])
    item.buyer_number = current_user.id
    item.save
    redirect_to "/items/#{item.id}/buy_done" 
  end
  
  private
  def item_params
    params.require(:item).permit(:name, :discription, :condition, :delivery_fee, :delivery_method, :delivery_days, :price, :size, :brand, :prefecture, :image, :status, :category).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/buy.html.haml
= render partial: './shared/new-header'
.check-contents
  .check-contents__container
    %h2 
    .check-contents__container__head 購入内容の確認
    .check-contents__container__item
      .check-contents__container__item__inner
        .check-contents__container__item__inner__image 
          = image_tag @item.image.url, class:"image",  size: "128x128"
        .check-contents__container__item__inner__name  
          = @item.name
        .check-contents__container__item__inner__kingaku
          .check-contents__container__item__inner__kingaku__price
            %p  
              ¥
              = @item.price
            .check-contents__container__item__inner__kingaku__price__shipping-fee  送料込み
        .check-contents__container__item__inner__buy-accordion
          .check-contents__container__item__inner__buy-accordion__parent
          .check-contents__container__item__inner__buy-accordion__toggle  ポイントはありません
        .check-contents__container__item__inner__table
          .check-contents__container__item__inner__table__cell  支払い金額
          .check-contents__container__item__inner__table__price
            ¥
            = @item.price
        = form_tag(action: :pay, method: :post ) do
          %script.payjp-button{:src => "https://checkout.pay.jp", :type => "text/javascript" ,"data-text" => "購入する" ,"data-key" => ENV['PAYJP_PUBLIC_KEY'] }
    .check-contents__container__info
      .check-contents__container__info__inner  配送先 
      .check-contents__container__info__text
        .check-contents__container__info__yuubin  〒541-0059 
        .check-contents__container__info__adress  大阪府 大阪市中央区博労町１町目７−９プレサンス心斎橋ブライト５０３号室
        .check-contents__container__info__name
          = current_user.family_name
          = current_user.first_name
        .check-contents__container__info__fix
          = link_to  do
            %span  変更する
    .check-contents__container__user-info
      .check-contents__container__user-info__inner
        %h3  支払い方法
        .check-contents__container__user-info__inner__text  
          ************4967 
          %br  06 / 23
        .check-contents__container__user-info__inner__figure 
          = image_tag "master-card.svg", class:"image", alt:"merucari",  size: "34x20"
        .check-contents__container__user-info__inner__fix
          = link_to  do
            %span  変更する
= render partial: './shared/new-footer'

app/views/items/buy_done.html.haml
= render partial: './shared/new-header'
.check-contents
  .check-contents__container
    .check-contents__container__done
      .check-contents__container__done__red
        発送をお待ちください
      .check-contents__container__done__black
        出品者からの発送通知をお待ちください
    %h2 
    .check-contents__container__head 購入が完了しました
    .check-contents__container__item
      .check-contents__container__item__inner
        .check-contents__container__item__inner__image 
          = image_tag @item.image.url, class:"image",  size: "128x128"
        .check-contents__container__item__inner__name 
          = @item.name
        .check-contents__container__item__inner__kingaku
          .check-contents__container__item__inner__kingaku__price
            %p 
              ¥
              = @item.price
            .check-contents__container__item__inner__kingaku__price__shipping-fee  送料込み
        .check-contents__container__item__inner__buy-accordion
          .check-contents__container__item__inner__buy-accordion__parent
          .check-contents__container__item__inner__buy-accordion__toggle  ポイントはありません
        .check-contents__container__item__inner__table
          .check-contents__container__item__inner__table__cell  支払い金額
          .check-contents__container__item__inner__table__price
            ¥
            = @item.price

    .check-contents__container__info
      .check-contents__container__info__inner  配送先 
      .check-contents__container__info__text
        .check-contents__container__info__yuubin  〒541-0059 
        .check-contents__container__info__adress  大阪府 大阪市中央区博労町１町目７−９プレサンス心斎橋ブライト５０３号室
        .check-contents__container__info__name
          = current_user.family_name
          = current_user.first_name
        .check-contents__container__info__fix
      
    .check-contents__container__user-info
      .check-contents__container__user-info__inner
        %h3  支払い方法
        .check-contents__container__user-info__inner__text  
          ************4967 
          %br  06 / 23
        .check-contents__container__user-info__inner__figure 
          = image_tag "master-card.svg", class:"image", alt:"merucari",  size: "34x20"
        .check-contents__container__user-info__inner__fix
        .done
          = link_to root_path do
            %span マイページに戻る

= render partial: './shared/new-footer'

app/views/items/card_add.html.haml
= render partial: "shared/topheader"
= render partial: "shared/pankuzukari"

.ohako
  .ohako__content
    .ohako__content__container
      %h2.ohako__content__container__head 支払い方法
      .ohako__content__container__inner
        %section
          .ohako__content__container__inner__content
            %h3.ohako__content__container__inner__content__head クレジットカード一覧
        %section.ohako__content__container__inner__card
          .ohako__content__container__inner__card__content
            .ohako__content__container__inner__card__content__button 
              = fa_icon 'credit-card'
              = link_to 'クレジットカードを追加する'

        .ohako__content__container__inner__regist
          = link_to '支払い方法について'
          = fa_icon 'angle-right'
            

  = render partial: "shared/mypageside"



= render partial: "shared/topfooter"

app/views/items/index.html.haml
%body
  .default-container
    %header.top-page-pc-header
      .top-page-pc-header__inner
        .top-page-pc-header__inner__top
          %h1.top-page-pc-header__inner__top__logo
            = link_to image_tag('top-header-logo.svg', class: "header-logo" ), root_path
          .header-search-form
            %input{class: "header-search-form__input", placeholder: "何かお探しですか？"}
              = link_to root_path, class:"header-search-button"  do
                .header-button-wrapper
                  = fa_icon 'search 2x', class: "search"
        .top-page-header-icon-lists
          .top-icon-list-left
            %ul.header-category-wrapper
              %li.header-icons
                %h2
                  = link_to root_path class:"pc-header-nav-rootlist-parent" do
                    = fa_icon("list-ul", class: "header-left-icon-logo")
                    %span.header-bold カテゴリーから探す
              %li.header-icons
                %h2
                  = link_to root_path, class:"pc-header-nav-root list-parent" do
                    = fa_icon("tag", class: "header-left-icon-logo")
                    %span.header-bold ブランドから探す
          .top-page-list-right
            -if user_signed_in?
              %ul.header-user-nav
                %li.header-info
                  = link_to root_path class: "header-info-link" do
                    = fa_icon("bell-o ")
                    %span.header-user-nav-text お知らせ
                %li.header-to-do
                  = link_to root_path class: "to_do-link" do
                    = fa_icon("check")
                    %span.header-user-nav-text やることリスト
                %li.header-mypage
                  = link_to user_path(current_user),method: :get, class: "header-my-page-link" do
                    = image_tag "mypage-image.png", class: "header-mypage-icon-image"
                    %span.header-user-nav-text-mypage マイページ
            -else
              %ul.header-login-nav
                %li.header-login-nav__login-button
                  = link_to "ログイン",   new_user_session_path, class: "header-login-nav__login-button__text"
                %li.header-login-nav__registration-button
                  = link_to "新規会員登録", users_sign_up_new_path, class: "header-login-nav__registration-button__text"

    .content-footer
      %section.content-footer__slide-box
        = image_tag "mercaricamp.png", class: "content-footer__slide-box__img"
      %section.pickup-container
        %h2.pickup-container__head
          ピックアップカテゴリー
        %section.item-box-container
          = link_to  root_path  do
            %h3.item-box-container__text-center レディース新着アイテム
          .item-box-content
            - @ladys.each do |item|
              %section.item-box
                = link_to item_path(item), method: :get do
                  .item-box__content-photo
                    = image_tag item.image.url, class: :"item-box__content-photo__img"
                    - if item.buyer_number
                      .soldout
                      .soldout__text
                        SOLD
                    - else
                      .none
                  .item-box__content-body
                    %h3.item-box__content-body__item-name 
                      = item.name
                    .item-box__content-body__num
                      .item-box__content-body__num__price
                        %p.item-box__content-body__num__price__text 
                          = "¥#{item.price}"
                      %div
                        %p.item-box__content-body__tax (税込)
          = link_to root_path do
            .item-box-content-view
              %p.item-box-content-view-all
                全ての商品を見る
                %section.item-box-container

          = link_to root_path do
            %h3.item-box-container__text-center メンズ 新着アイテム
          .item-box-content
            - @mens.each do |item|
              %section.item-box
                = link_to item_path(item), method: :get do
                  .item-box__content-photo
                    = image_tag item.image.url, class: :"item-box__content-photo__img"
                    - if item.buyer_number
                      .soldout
                      .soldout__text
                        SOLD
                    - else
                      .none
                  .item-box__content-body
                    %h3.item-box__content-body__item-name 
                      = item.name
                    .item-box__content-body__num
                      .item-box__content-body__num__price
                        %p.item-box__content-body__num__price__text 
                          = "¥#{item.price}"
                      %div
                        %p.item-box__content-body__tax (税込)
          = link_to root_path do
            .item-box-content-view
              %p.item-box-content-view-all
                全ての商品を見る
                %section.item-box-container

          = link_to root_path do
            %h3.item-box-container__text-center ベビー・キッズ 新着アイテム
          .item-box-content
            - @babys.each do |item|
              %section.item-box
                = link_to item_path(item), method: :get do
                  .item-box__content-photo
                    = image_tag item.image.url, class: :"item-box__content-photo__img"
                    - if item.buyer_number
                      .soldout
                      .soldout__text
                        SOLD
                    - else
                      .none
                  .item-box__content-body
                    %h3.item-box__content-body__item-name 
                      = item.name
                    .item-box__content-body__num
                      .item-box__content-body__num__price
                        %p.item-box__content-body__num__price__text 
                          = "¥#{item.price}"
                      %div
                        %p.item-box__content-body__tax (税込)
          = link_to root_path do
            .item-box-content-view
              %p.item-box-content-view-all
                全ての商品を見る
                %section.item-box-container

        %section.item-box-container
          = link_to root_path do
            %h3.item-box-container__text-center コスメ・香水・美容 新着アイテム
          .item-box-content
            - @biyous.each do |item|
              %section.item-box
                = link_to item_path(item), method: :get do
                  .item-box__content-photo
                    = image_tag item.image.url, class: :"item-box__content-photo__img"
                    - if item.buyer_number
                      .soldout
                      .soldout__text
                        SOLD
                    - else
                      .none
                  .item-box__content-body
                    %h3.item-box__content-body__item-name 
                      = item.name
                    .item-box__content-body__num
                      .item-box__content-body__num__price
                        %p.item-box__content-body__num__price__text 
                          = "¥#{item.price}"
                      %div
                        %p.item-box__content-body__tax (税込)
          = link_to root_path do
            .item-box-content-view
              %p.item-box-content-view-all
                全ての商品を見る
                %section.item-box-container

            
        %h2.pickup-container__head
          ピックアップブランド
        %section.item-box-container
          = link_to root_path do
            %h3.item-box-container__text-center シャネル 新着アイテム
          .item-box-content
            - @shanels.each do |item|
              %section.item-box
                = link_to item_path(item), method: :get do
                  .item-box__content-photo
                    = image_tag item.image.url, class: :"item-box__content-photo__img"
                    - if item.buyer_number
                      .soldout
                      .soldout__text
                        SOLD
                    - else
                      .none
                  .item-box__content-body
                    %h3.item-box__content-body__item-name 
                      = item.name
                    .item-box__content-body__num
                      .item-box__content-body__num__price
                        %p.item-box__content-body__num__price__text 
                          = "¥#{item.price}"
                      %div
                        %p.item-box__content-body__tax (税込)
          = link_to root_path do
            .item-box-content-view
              %p.item-box-content-view-all
                全ての商品を見る
                %section.item-box-container

      .app-banner
        = image_tag "banar-image.png", class: "app-banar-img"
      %footer.footer-top-page
        .footer-box
          .footer-cell
            %h2.footer-cell__head メルカリについて
            %ul
              %li.footer-cell__footer-top-text-normal 会社概要 (運営会社)
              %li.footer-cell__normal 採用情報
              %li.footer-cell__normal プレリリース
              %li.footer-cell__normal 公式ブログ
              %li.footer-cell__normal メルカリロゴ利用ガイドライン
              %li.footer-cell__sns-link
                = fa_icon 'twitter', class: "twitter-logo"
              %li.footer-cell__sns-link
                = fa_icon 'facebook-square', class: "twitter-logo"
          .footer-cell
            %h2.footer-cell__head ヘルプ＆ガイド
            %ul
              %li.footer-cell__footer-top-text-normal メルカリガイド
              %li.footer-cell__normal 楽々メルカリ便
              %li.footer-cell__normal ゆうゆうメルカリ便
              %li.footer-cell__normal 大型メルカリ便
              %li.footer-cell__normal 車体取引ガイド
              %li.footer-cell__normal メルカリあんしん・あんぜん宣言
              %li.footer-cell__normal 偽ブランド品撲滅への取り組み
              %li.footer-cell__normal メルカリボックス
          .footer-cell-full-width
            %h2.footer-cell-full-width__head プライバシーと利用規約
            .footer-cell-full-width__cell-wrapper
              .footer-cell-full-width__cell-wrapper__cell-left
                %ul
                  %li.footer-cell-full-width__cell-wrapper__cell-left__top-text-normal プライバシーポリシー
                  %li.footer-cell-full-width__cell-wrapper__cell-left__normal メルカリ利用規約
                  %li.footer-cell-full-width__cell-wrapper__cell-left__normal あんしんスマホサポート制度に関する利用規約
                  %li.footer-cell-full-width__cell-wrapper__cell-left__normal コンプライアンスポリシー
              .footer-cell-full-width__cell-wrapper__cell-right
                %ul
                  %li.footer-cell-full-width__cell-wrapper__cell-right__top-text-normal 個人データの安全管理に係る基本方針
                  %li.footer-cell-full-width__cell-wrapper__cell-right__normal 特定商取引に関する表記
                  %li.footer-cell-full-width__cell-wrapper__cell-right__normal 資金決済法に基づく表示
                  %li.footer-cell-full-width__cell-wrapper__cell-right__normal 法令遵守と犯罪抑止のために
                  %li.footer-cell-full-width__cell-wrapper__cell-right__normal 返品・返金ポリシー
          .fotter-cell-lang
            %h2.footer-cell__head 国
            %ul
              %li.footer-head-jp 日本
              %li.footer-head-us United Status
        .footer-bottom
          = link_to root_path class:"footer-logo-link" do
            - image_tag "logo-white.svg", class: "footer-logo-link-image"
          %span.footer-copyrifght © 2019 Mercari
      - if user_signed_in?
        = link_to new_item_path , class: "footer-sell-btn" do
          .footer-sell-btn__text 出品
          = fa_icon "camera", class: "camera-icon"
      - else
        = link_to new_user_session_path , class: "footer-sell-btn" do
          .footer-sell-btn__text 出品
          = fa_icon "camera", class: "camera-icon"

app/views/items/mypagehonninkakunin.html.haml
= render partial: "shared/topheader"
= render partial: "shared/pankuzukari"

.ohako
  = render partial: "shared/mypageside"
  .honnin
    .honbox
      .honbox__head
        本人情報の登録
      .honbox__main
        = form_with url: root_path,local: true , class: "sampleform" do |f|
          %p.honbox__main__head
            お客様の本人情報をご登録ください。<br>
            登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
          %a.honbox__main__caution{href: :"root_path"}
            本人確認書類のアップロードについて&emsp;＞
          .honbox__main__formbox
            %label.honbox__main__formbox__label
              お名前
            %p.honbox__main__formbox__content
              大橋      
          .honbox__main__formbox
            %label.honbox__main__formbox__label
              お名前カナ
            %p.honbox__main__formbox__content
              オオハシ
          .honbox__main__formbox
            %label.honbox__main__formbox__label
              生年月日
            %p.honbox__main__formbox__content
              1990/01/01
          .honbox__main__formbox
            %label.honbox__main__formbox__label
              郵便番号
            %span.honbox__main__formbox__nini
              任意
            = f.text_field :keyword, class: 'honbox__main__formbox__form', placeholder: '例）1234567'
          .honbox__main__formbox
            %label.honbox__main__formbox__label
              都道府県
            %span.honbox__main__formbox__nini
              任意
            %select.honbox__main__formbox__prefec
              <option value="--">--</option>
              <option value="1">北海道</option>
              <option value="2">青森県</option>
              <option value="3">岩手県</option>
              <option value="4">宮城県</option>
          .honbox__main__formbox
            %label.honbox__main__formbox__label
              市区町村
            %span.honbox__main__formbox__nini
              任意
            = f.text_field :keyword, class: 'honbox__main__formbox__form', placeholder: '例) 横浜市緑区'
          .honbox__main__formbox
            %label.honbox__main__formbox__label
              番地
            %span.honbox__main__formbox__nini
              任意
            = f.text_field :keyword, class: 'honbox__main__formbox__form', placeholder: '例) 青山1-1-1'
          .honbox__main__formbox
            %label.honbox__main__formbox__label
              建物名
            %span.honbox__main__formbox__nini
              任意
            = f.text_field :keyword, class: 'honbox__main__formbox__form', placeholder: '例) 柳ビル103'
          %button.honbox__main__btn
            登録する
          %a.honbox__main__caution{href: :"root_path"}
            本人確認書類のアップロードについて&emsp;＞


= render partial: "shared/topfooter"

app/views/items/mypagelogout.html.haml
= render partial: "shared/topheader"
= render partial: "shared/pankuzukari"

.ohako
  = render partial: "shared/mypageside"
  .logoutbox
    %form.logoutbox__form{action: :"https://www.mercari.com/jp/logout/", method: :"POST", novalidate: :"novalidate"}
      .logoutbox__form__content
        %button.logoutbox__form__content__btn{type: :"submit"} ログアウト
        %input{name: :"__csrf_value", type: :"hidden", value: :"d9163badd600f0759504f3c3d03fe90dc77553d7088130fd36fa09442be89f9495ac622fcdb8d50c719900926f76df4a48027fd1afba1c82a96b2020dff2aff06"}/



= render partial: "shared/topfooter"

app/views/items/mypageprofile.html.haml
= render partial: "shared/topheader"
= render partial: "shared/pankuzukari"

.ohako
  = render partial: "shared/mypageside"
  .profilebox
    .profilebox__head プロフィール
    %form{action: :"https://www.mercari.com/jp/mypage/profile/", method: :"POST"}
      %input{name: :"__csrf_value",type: :"hidden", value: :"d9163badd600f0759504f3c3d03fe90dc77553d7088130fd36fa09442be89f9495ac622fcdb8d50c719900926f76df4a48027fd1afba1c82a96b2020dff2aff06"}/
      .profilebox__avname
        .profilebox__avname__av
          = image_tag "user_noimage.png", size: :'60x60' 
        %input.profilebox__avname__name{name: :"nickname", placeholder: :"例)AYA☆セール中", type: :"text", value: :"大橋"}/
      .profilebox__content
        %textarea.profilebox__content__text{name: :"introduction", placeholder: :"例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
        %input{name: :"after_save_callback", type: :"hidden", value: :"https://www.mercari.com/jp/mypage/profile/"}/
        %button.profilebox__content__btn{type: :"submit"} 変更する
= render partial: "shared/topfooter"

app/views/items/registration05.html.haml
= render partial: './shared/new-header'
.pay-page-single-main
  .pay-conatainer
    %h2.pay-conatainer__head
      会員登録完了
    .pay-conatainer__inner
      .pay-conatainer__inner__content
        .pay-conatainer__inner__content__margin-box
        .pay-conatainer__inner__content__text-box
          %p.pay-conatainer__inner__content__text-box__text
          ありがとうございます
          %p.pay-conatainer__inner__content__text-box__text
          会員登録が完了しました
      .pay-conatainer__inner__content
        %input{type: "hidden", method: "POST"}
        %button{type: "submit", class:"nextbtn-red"}
          メルカリを始める
= render partial: './shared/new-footer'

app/views/items/registraton05.html.haml
= render partial: './shared/new-header'
.pay-page-single-main
  .pay-conatainer
    %h2.pay-conatainer__head
      会員登録完了
    .pay-conatainer__inner
      .pay-conatainer__inner__content
        .pay-conatainer__inner__content__margin-box
        .pay-conatainer__inner__content__text-box
          %p.pay-conatainer__inner__content__text-box__text
          ありがとうございます
          %p.pay-conatainer__inner__content__text-box__text
          会員登録が完了しました
      .pay-conatainer__inner__content
        %input{type: "hidden", method: "POST"}
        %button{type: "submit", class:"nextbtn-red"}
          メルカリを始める
= render partial: './shared/new-footer'